deepmikoto_api_coding_timeline:
    path:     /coding-timeline
    defaults: { _controller: DeepMikotoApiBundle:Coding:codingTimeline }
deepmikoto_api_coding_categories:
    path:     /coding-categories
    defaults: { _controller: DeepMikotoApiBundle:Coding:codingCategories }
deepmikoto_api_coding_category_timeline:
    path:     /coding-category-timeline
    defaults: { _controller: DeepMikotoApiBundle:Coding:codingCategoryTimeline }
deepmikoto_api_coding_post:
    path:     /coding-post
    defaults: { _controller: DeepMikotoApiBundle:Coding:codingPost }