imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        site_title:   deepmikoto
        google_api_key: "%google_api_key%"
        fb_app_id: "%fb_app_id%"
        push_public_key: "%push_public_key%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
    bundles:        [ DeepMikotoApiBundle, TwigBundle, DeepMikotoAdminBundle ]
    #java: /usr/bin/java
    ruby: %ruby_path%
    filters:
        cssrewrite: ~
        sass:
            bin: %sass_bin%
            apply_to: '\.scss$'
        compass:
            bin: %compass_bin%
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
            timeout: 3600
            apply_to: '\.css$'
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
            timeout: 3600

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#doctrine migrations
doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

#liip imagine bundle filters
liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        sidebar_primary_block:
            quality: 90
            filters:
                thumbnail: { size: [370, 370], mode: inset }
        tiny_thumb:
            quality: 80
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        tiny_thumb_no_crop:
            quality: 80
            filters:
                thumbnail: { size: [64, 64], mode: inset }
        timeline_picture:
            quality: 80
            filters:
                thumbnail: { size: [470, 310], mode: outbound }
        gaming_timeline_picture:
            quality: 80
            filters:
                thumbnail: { size: [820, 600], mode: inset }
        r_30_30:
            quality: 80
            filters:
                thumbnail: { size: [30, 30], mode: inset }
        r_20_20:
            quality: 80
            filters:
                thumbnail: { size: [20, 20], mode: inset }
        r_200_200:
            quality: 80
            filters:
                thumbnail: { size: [200, 200], mode: inset }

minishlink_web_push:
  api_keys:
    GCM: "%push_public_key%"
  VAPID:
    subject: "https://deepmikoto.com"
    publicKey: "%push_public_key%"
    privateKey: "%push_private_key%"
    #pemFile: path/to/pem          # if you have a PEM file and can link to it on your filesystem
    #pem: pemFileContent           # if you have a PEM file and want to hardcode its content
  ttl: 2419200                    # Time to Live of notifications in seconds
  urgency: ~                      # can be very-low / low / normal / high
  topic: ~                        # default identifier for your notifications
  timeout: 30                     # Timeout of each request in seconds
  automatic_padding: true