imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        site_title:   deepmikoto
        google_api_key: "%google_api_key%"
        fb_app_id: "%fb_app_id%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ DeepMikotoApiBundle, TwigBundle, DeepMikotoAdminBundle ]
    #java: /usr/bin/java
    ruby: %ruby_path%
    filters:
        cssrewrite: ~
        sass:
            bin: %sass_bin%
            apply_to: "\.s[ac]ss$"
        compass:
            bin: %compass.bin%
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
            apply_to: "\.css$"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
            apply_to: "\.js$"

#doctrine migrations
doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

#liip imagine bundle filters
liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        sidebar_primary_block:
            quality: 90
            filters:
                thumbnail: { size: [370, 370], mode: inset }
        tiny_thumb:
            quality: 80
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        timeline_picture:
            quality: 80
            filters:
                thumbnail: { size: [470, 310], mode: outbound }
        gaming_timeline_picture:
            quality: 80
            filters:
                thumbnail: { size: [820, 600], mode: inset }
        30_30:
            quality: 80
            filters:
                thumbnail: { size: [30, 30], mode: inset }
