_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
deepmikoto_admin:
    resource: "@DeepMikotoAdminBundle/Resources/config/routing.yml"
    prefix:   /adminarea

deepmikoto_app:
    resource: "@DeepMikotoApiBundle/Resources/config/routing.yml"
    prefix:   /


