_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
deepmikoto_admin:
    resource: "@DeepMikotoAdminBundle/Resources/config/routing.yml"
    prefix:   /adminarea

app_dev_php:
    path: /app_dev.php
    defaults: { _controller: DeepMikotoAdminBundle:Security:login }
deepmikoto_app:
    resource: "@DeepMikotoApiBundle/Resources/config/routing.yml"
    prefix:   /


