deepmikoto_api_templates:
    path:     /templates
    defaults: { _controller: DeepMikotoApiBundle:Api:templates }
deepmikoto_api_user_info:
    path:     /user-info
    defaults: { _controller: DeepMikotoApiBundle:Api:userInfo }