deepmikoto_sidebar:
    resource: "@DeepMikotoApiBundle/Resources/config/routes/api_components/sidebar.yml"
    prefix:   /
deepmikoto_header:
    resource: "@DeepMikotoApiBundle/Resources/config/routes/api_components/header.yml"
    prefix:   /
deepmikoto_coding:
    resource: "@DeepMikotoApiBundle/Resources/config/routes/api_components/coding.yml"
    prefix:   /
deepmikoto_gaming:
    resource: "@DeepMikotoApiBundle/Resources/config/routes/api_components/gaming.yml"
    prefix:   /
deepmikoto_photography:
    resource: "@DeepMikotoApiBundle/Resources/config/routes/api_components/photography.yml"
    prefix:   /
deepmikoto_api_templates:
    path:     /templates
    defaults: { _controller: DeepMikotoApiBundle:Api:templates }
deepmikoto_api_help_page:
    path:     /help
    defaults: { _controller: DeepMikotoApiBundle:Api:helpPage }