deepmikoto_app_homepage:
    path:     /
    defaults: { _controller: DeepMikotoApiBundle:Api:index }

deepmikoto_app_logout:
    path:     /logout

deepmikoto_app_all_routes_redirect:
    path:     /{param}
    defaults: { _controller: DeepMikotoApiBundle:Api:index }