deepmikoto_app_homepage:
    path:     /
    defaults: { _controller: DeepMikotoApiBundle:App:home }
deepmikoto_app_photography:
    path:     /photography
    defaults: { _controller: DeepMikotoApiBundle:App:photography }
deepmikoto_app_photography_post:
    path:     /photography/{id}--{slug}
    defaults: { _controller: DeepMikotoApiBundle:App:photographyPost, id:null, slug:null }
deepmikoto_app_coding:
    path:     /coding
    defaults: { _controller: DeepMikotoApiBundle:App:coding }
deepmikoto_app_coding_demo_page:
    path:     /coding/demo-{slug}
    defaults: { _controller: DeepMikotoApiBundle:App:codingDemoPage }
deepmikoto_app_coding_categories:
    path:     /coding/categories
    defaults: { _controller: DeepMikotoApiBundle:App:codingCategories }
deepmikoto_app_coding_post:
    path:     /coding/{id}--{slug}
    defaults: { _controller: DeepMikotoApiBundle:App:codingPost, id:null, slug:null }
deepmikoto_app_coding_posts_by_category:
    path:     /coding/{category}
    defaults: { _controller: DeepMikotoApiBundle:App:codingPostsByCategory }
deepmikoto_app_gaming:
    path:     /gaming
    defaults: { _controller: DeepMikotoApiBundle:App:gaming }
deepmikoto_app_gaming_post:
    path:     /gaming/{id}--{slug}
    defaults: { _controller: DeepMikotoApiBundle:App:gamingPost, id:null, slug:null }
deepmikoto_app_help_page:
    path:     /help
    defaults: { _controller: DeepMikotoApiBundle:App:helpPage }
deepmikoto_app_facebook_test:
    path:     /facebook-test/{slug}
    defaults: { _controller: DeepMikotoApiBundle:App:facebookTest }
deepmikoto_app_logout:
    path:     /logout
