deepmikoto_app_homepage:
    path:     /
    defaults: { _controller: DeepMikotoApiBundle:App:home }
deepmikoto_app_photography:
    path:     /photography
    defaults: { _controller: DeepMikotoApiBundle:App:photography }
deepmikoto_app_coding:
    path:     /coding
    defaults: { _controller: DeepMikotoApiBundle:App:coding }
deepmikoto_app_gaming:
    path:     /gaming
    defaults: { _controller: DeepMikotoApiBundle:App:gaming }

deepmikoto_app_logout:
    path:     /logout
