deepmikoto_app:
    resource: "@DeepMikotoApiBundle/Resources/config/routes/_app.yml"
    prefix:   /

deepmikoto_api:
    resource: "@DeepMikotoApiBundle/Resources/config/routes/_api.yml"
    prefix:   /_api
