services:
    deepmikoto.api:
        class: DeepMikoto\ApiBundle\Services\ApiService
        arguments: [ "@service_container", "@doctrine.orm.entity_manager", "@request_stack", "@serializer" ]
    deepmikoto.api.templating:
        class: DeepMikoto\ApiBundle\Services\TemplatingService
        arguments: [ "@templating", "@serializer" ]
    deepmikoto.api.sidebar_manager:
        class: DeepMikoto\ApiBundle\Services\SidebarService
        arguments: [ "@service_container", "@doctrine.orm.entity_manager", "@request_stack" ]
    deepmikoto.api.coding_manager:
        class: DeepMikoto\ApiBundle\Services\CodingService
        arguments: [ "@doctrine.orm.entity_manager" ]
    deepmikoto.api.photography_manager:
        class: DeepMikoto\ApiBundle\Services\PhotographyService
        arguments: [ "@service_container", "@doctrine.orm.entity_manager", "@router" ]
    deepmikoto.api.gaming_manager:
        class: DeepMikoto\ApiBundle\Services\GamingService
        arguments: [ "@service_container", "@doctrine.orm.entity_manager" ]