deepmikoto_admin_coding:
    path:     /
    defaults: { _controller: DeepMikotoAdminBundle:Coding:index }
deepmikoto_admin_coding_primary_block:
    path:     /primary-block
    defaults: { _controller: DeepMikotoAdminBundle:Coding:primaryBlock }
deepmikoto_admin_coding_new_post:
    path:     /new-post
    defaults: { _controller: DeepMikotoAdminBundle:Coding:newPost }
deepmikoto_admin_coding_edit_post:
    path:     /edit-post-{id}
    defaults: { _controller: DeepMikotoAdminBundle:Coding:editPost }
    requirements:
        id:  \d+
deepmikoto_admin_coding_submitted_posts:
    path:     /submitted-posts
    defaults: { _controller: DeepMikotoAdminBundle:Coding:submittedPosts }
deepmikoto_admin_coding_drafted_posts:
    path:     /drafted-posts
    defaults: { _controller: DeepMikotoAdminBundle:Coding:draftedPosts }
deepmikoto_admin_coding_make_public_or_drafted:
    path:     /make-public-or-drafted/{id}-{public}
    defaults: { _controller: DeepMikotoAdminBundle:Coding:makePublicOrDrafted }
    requirements:
        id:  \d+
deepmikoto_admin_coding_categories:
    path:     /categories
    defaults: { _controller: DeepMikotoAdminBundle:Coding:categories }
deepmikoto_admin_coding_add_category:
    path:     /add-category
    defaults: { _controller: DeepMikotoAdminBundle:Coding:addCategory }
deepmikoto_admin_coding_edit_category:
    path:     /edit-category/{id}
    defaults: { _controller: DeepMikotoAdminBundle:Coding:editCategory }
    requirements:
        id:  \d+
deepmikoto_admin_delete_coding_post:
    path:     /delete/{id}
    defaults: { _controller: DeepMikotoAdminBundle:Coding:deletePost }
    requirements:
        id:  \d+