deepmikoto_admin_gaming:
    path:     /
    defaults: { _controller: DeepMikotoAdminBundle:Gaming:index }
deepmikoto_admin_gaming_primary_block:
    path:     /primary-block
    defaults: { _controller: DeepMikotoAdminBundle:Gaming:primaryBlock }
deepmikoto_admin_gaming_new_post:
    path:     /new-post
    defaults: { _controller: DeepMikotoAdminBundle:Gaming:newPost }
deepmikoto_admin_gaming_edit_post:
    path:     /edit-post-{id}
    defaults: { _controller: DeepMikotoAdminBundle:Gaming:editPost }
    requirements:
        id:  \d+
deepmikoto_admin_gaming_new_photo:
    path:     /new-photo
    defaults: { _controller: DeepMikotoAdminBundle:Gaming:newGamingPhoto }
deepmikoto_admin_gaming_edit_photo:
    path:     /edit-photo-{id}
    defaults: { _controller: DeepMikotoAdminBundle:Gaming:editGamingPhoto }
    requirements:
        id:  \d+
deepmikoto_admin_gaming_photos:
    path:     /photos
    defaults: { _controller: DeepMikotoAdminBundle:Gaming:gamingPhotos }
deepmikoto_admin_gaming_submitted_posts:
    path:     /submitted-posts
    defaults: { _controller: DeepMikotoAdminBundle:Gaming:submittedPosts }
deepmikoto_admin_gaming_drafted_posts:
    path:     /drafted-posts
    defaults: { _controller: DeepMikotoAdminBundle:Gaming:draftedPosts }
deepmikoto_admin_gaming_make_public_or_drafted:
    path:     /make-public-or-drafted/{id}-{public}
    defaults: { _controller: DeepMikotoAdminBundle:Gaming:makePublicOrDrafted }
    requirements:
        id:  \d+
deepmikoto_admin_delete_gaming_post:
    path:     /delete/{id}
    defaults: { _controller: DeepMikotoAdminBundle:Gaming:deletePost }
    requirements:
        id:  \d+