deepmikoto_admin_homepage:
    path:     /
    defaults: { _controller: DeepMikotoAdminBundle:Home:index }
deepmikoto_admin_help_page:
    path:     /help-page
    defaults: { _controller: DeepMikotoAdminBundle:Home:helpPage }
deepmikoto_admin_help_page_edit:
    path:     /help-page-edit
    defaults: { _controller: DeepMikotoAdminBundle:Home:helpPageEdit }
deepmikoto_admin_administration:
    path:     /administration
    defaults: { _controller: DeepMikotoAdminBundle:Home:administration }