deepmikoto_admin_homepage:
    path:     /
    defaults: { _controller: DeepMikotoAdminBundle:Home:index }
deepmikoto_admin_primary_block:
    path:     /primary-block
    defaults: { _controller: DeepMikotoAdminBundle:Home:primaryBlock }