deepmikoto_admin_photography:
    path:     /
    defaults: { _controller: DeepMikotoAdminBundle:Photography:index }
deepmikoto_admin_photography_primary_block:
    path:     /primary-block
    defaults: { _controller: DeepMikotoAdminBundle:Photography:primaryBlock }
deepmikoto_admin_photography_new_post:
    path:     /new-post
    defaults: { _controller: DeepMikotoAdminBundle:Photography:newPost }
deepmikoto_admin_photography_edit_post:
    path:     /edit-post-{id}
    defaults: { _controller: DeepMikotoAdminBundle:Photography:editPost }
    requirements:
        id:  \d+
deepmikoto_admin_photography_new_post_photo:
    path:     /new-post-photo
    defaults: { _controller: DeepMikotoAdminBundle:Photography:newPostPhoto }
deepmikoto_admin_photography_edit_post_photo:
    path:     /edit-post-photo/{id}
    defaults: { _controller: DeepMikotoAdminBundle:Photography:editPostPhoto }
    requirements:
        id:  \d+
deepmikoto_admin_photography_post_photo_list:
    path:     /post-photo-list
    defaults: { _controller: DeepMikotoAdminBundle:Photography:postPhotoList }
deepmikoto_admin_photography_submitted_posts:
    path:     /submitted-posts
    defaults: { _controller: DeepMikotoAdminBundle:Photography:submittedPosts }
deepmikoto_admin_photography_drafted_posts:
    path:     /drafted-posts
    defaults: { _controller: DeepMikotoAdminBundle:Photography:draftedPosts }
deepmikoto_admin_photography_make_public_or_drafted:
    path:     /make-public-or-drafted/{id}-{public}
    defaults: { _controller: DeepMikotoAdminBundle:Photography:makePublicOrDrafted }
    requirements:
        id:  \d+
deepmikoto_admin_delete_photography_post:
    path:     /delete/{id}
    defaults: { _controller: DeepMikotoAdminBundle:Photography:deletePost }
    requirements:
        id:  \d+
deepmikoto_admin_delete_photography_photo:
    path:     /delete-photo/{id}
    defaults: { _controller: DeepMikotoAdminBundle:Photography:deletePhoto }
    requirements:
        id:  \d+