dizda_cloud_backup:
    # By default backup files will have your servers hostname as prefix
    # such as: hostname_2014-01-01_21-08-39.tar
    output_file_prefix: deepmikoto.com
    timeout: 300
    restore: true # Set to true to enable restore command
    processor:
        type: zip # Required: tar|zip|7z
        options:
            compression_ratio: 6
            password: '%dizda_cloud_archive_password%'
    folders: [ web/images/coding, web/images/gaming, web/images/photography ]
    cloud_storages:
        dropbox_sdk:
            remote_path: /deepmikoto.com
            access_token: '%dropbox_accesss_token%' # Required. Access token provided by DropBox to authenticate your application. You can follow instructions at https://www.dropbox.com/developers/core/start/php

    databases:
        mysql:
            all_databases: false # Only required when no database is set
            database: '%database_name%'